// This file has been generated by Specta. Do not edit this file manually.
/**  An action, deserialised from the plugin manifest. */
export type Action = {
	name: string,
	uuid: string,
	plugin: string,
	tooltip: string,
	icon: string,
	disable_automatic_states: boolean,
	visible_in_action_list: boolean,
	supported_in_multi_actions: boolean,
	property_inspector: string,
	controllers: string[],
	states: ActionState[],
};

/**  An instance of an action. */
export type ActionInstance = {
	action: Action,
	context: string,
	states: ActionState[],
	current_state: number,
	settings: any,
	children: ActionInstance[] | null,
};

/**  A state of an action. */
export type ActionState = {
	image: string,
	image_scale: number,
	background_colour: string,
	name: string,
	text: string,
	show: boolean,
	colour: string,
	stroke_colour: string,
	alignment: string,
	family: string,
	style: string,
	size: number,
	stroke_size: number,
	underline: boolean,
};

export type Category = {
	icon: string | null,
	actions: Action[],
};

/**  Location metadata of a slot. */
export type Context = {
	device: string,
	profile: string,
	controller: string,
	position: number,
};

/**  Metadata of a device. */
export type DeviceInfo = {
	id: string,
	plugin: string,
	name: string,
	rows: number,
	columns: number,
	encoders: number,
	touchpoints: number,
	type: number,
};

export type Profile = {
	id: string,
	keys: (ActionInstance | null)[],
	sliders: (ActionInstance | null)[],
	num_pages: number,
};

export type Settings = {
	version: string,
	language: string,
	brightness: number,
	sleep_timeout_minutes: number,
	rotation: number,
	background: boolean,
	autolaunch: boolean,
	updatecheck: boolean,
	statistics: boolean,
	separatewine: boolean,
	developer: boolean,
	disableelgato: boolean,
};
